# Helpers:
## Note: Top-level .keys are ignored by GitLab
.ruby_job: &ruby_job
  cache:
    key: bundler
    paths:
      - .bundle/
  before_script:
    - rbenv install -s > /dev/null
    - (bundle -v || gem install bundler) > /dev/null
    - bundle install --local --path .bundle --quiet

.javascript_job: &javascript_job
  cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    paths:
      - client/node_modules/
  before_script:
    - cd client
    - nvm use
    - (yarn --version || npm install --global yarn)
    - yarn install
    - cp api_key.example.js api_key.js

# Jobs:
brakeman:
  <<: *ruby_job
  script:
    - bundle exec brakeman -A -o brakeman.html
  artifacts:
    paths:
      - brakeman.html

bundler_audit:
  <<: *ruby_job
  script:
    - echo 'Ignoring CVE-2015-8314 as we do not use "Remember me" cookies with XACT...'
    - echo 'Ignoring CVE-2016-4658 and CVE-2016-5131 as we do not XACT like that'
    - bundle exec bundle-audit check --update --verbose --ignore CVE-2015-8314 CVE-2016-4658 CVE-2016-5131

rubocop:
  <<: *ruby_job
  script:
    - bundle exec rubocop --format simple --rails app features spec config bin

mocha:
  <<: *javascript_job
  script:
    - yarn test

eslint:
  <<: *javascript_job
  script:
    - yarn lint

