Metrics/LineLength:
  Enabled: false
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FileName:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/MethodLength:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/SignalException:
  Enabled: false
