---
sample_subscriber_number: '+16122236629'
test_support:
  twilio_xact_test_number: '+17014842689'
  twilio_xact_test_number_2: '+17014842689'
  mblox:
    phone:
      number: '+16122546317'
  twilio:
    phone:
      number: '+19138719228'
      sid: 'PN737ad7753ece587e2f2f72dd7ba5e459'
    account:
      sid: 'ACa26eb1ef3dc06c86333e4e9833af4c6b'
      token: '1f52e2578c65b9069ee3610d15ff87d7'
      twilio_test: false
sms_vendors:
  # live:                     # is env-specific
  loopback:
    phone:
      number: '+15552287439'   # 1-555-BBushey --or-- 1-555-CatShew --or-- 1-555-BatsHey
    vendor:
      username: 'shared_loopback_sms_username'
      password: 'dont care'
      shared: true
      twilio_test: false
  twilio_valid_test:
    phone:
      number: '+15005550006'
    vendor:
      username: 'ACc66477e37af9ebee0f12b349c7b75117'
      password: '5b1c96ca034d474c6d4b68f8d05c99f5'
      shared: true
      twilio_test: false
  #kahlo_loopback:
voice_vendors:
  # live:                     # is env-specific
  loopback:
    phone:
      number: '+15552287439'   # 1-555-BBushey --or-- 1-555-CatShew --or-- 1-555-BatsHey
    vendor:
      username: 'shared_loopback_voice_username'
      password: 'dont care'
      shared: true
      twilio_test: false
accounts:
 # account_name:
 # prefix:
 # xact:
 #   account_id:
 #   token:
 #   email_address:
 #   dcm_account_id:
 #   dcm_account_codes: []
  sms_keyword_commands_forward_worker:
    prefix: 'sms_2way_cdc'
  sms_keyword_commands_static:
    prefix: 'sms_2way_static'
  sms_keyword_commands_stop:
    prefix: 'sms_2way_stop'
  sms_keyword_commands_subscribe:
    prefix: 'sms_2way_subscribe'
  sms_end_to_end:
    sms_prefix: 'sms_end_to_end'
  email_endtoend:   #loopback
    xact:
      from_name_two: 'from_address_level_from_name'
    gmail:
      imap:
        address: 'imap.gmail.com'
        port:  993
        password: 'govdel01!'
        enable_ssl: true

gmail:
  address: 'xactqctest1@gmail.com'
  password: 'govdel01!'

voice:
  play_urls:
    - http://xact-webhook-callbacks.herokuapp.com/voice/first.mp3
    - http://xact-webhook-callbacks.herokuapp.com/voice/second.mp3
    - http://xact-webhook-callbacks.herokuapp.com/voice/third.mp3
    - http://xact-webhook-callbacks.herokuapp.com/voice/fourth.mp3
    - http://xact-webhook-callbacks.herokuapp.com/voice/fifth.mp3
    - http://xact-webhook-callbacks.herokuapp.com/voice/sixth.mp3
    - http://xact-webhook-callbacks.herokuapp.com/voice/seventh.mp3
    - http://xact-webhook-callbacks.herokuapp.com/voice/eighth.mp3
    - http://xact-webhook-callbacks.herokuapp.com/voice/ninth.mp3
    - http://xact-webhook-callbacks.herokuapp.com/voice/tenth.mp3
  recipient:
    number: '+16124679346'
    secondary_number: '+16123145807'

webhooks:
  magic:
    email:
      sending: 'sending@sink.govdelivery.com'
      sent: 'sent@sink.govdelivery.com'
      failed: 'failed@sink.govdelivery.com'
      blacklisted: 'blacklisted@sink.govdelivery.com'
      inconclusive: 'inconclusive@sink.govdelivery.com'
      canceled: 'canceled@sink.govdelivery.com'
    phone:
      sending: '15005550001'
      inconclusive: '15005550002'
      canceled: '15005550003'
      failed: '15005550004'
      blacklisted: '15005550005'
      sent: '15005550006'
