---
sms_vendors:
  kahlo_loopback:
    account:
      id: 10000
      token: JskrHxU8yTy8m4SYvmWq8y7Qep4ofTUh

accounts:
  sms_keyword_commands_forward_worker:
    xact:
      account_id: <%= ENV['XACT_SMS2WAYCDC_ACCOUNT_ID'] %>
      token: <%= ENV['XACT_SMS2WAYCDC_USER_TOKEN'] %>
      email_address: 'development-sms_2way_cdc-test@govdelivery.com'
  sms_keyword_commands_static:
    xact:
      account_id: <%= ENV['XACT_SMS2WAYSTATIC_ACCOUNT_ID'] %>
      token: <%= ENV['XACT_SMS2WAYSTATIC_USER_TOKEN'] %>
      email_address: 'development-sms_2way_static-test@govdelivery.com'
  webhooks:
    xact:
      account:
        id:  <%= ENV['XACT_WEBHOOK_ACCOUNT_ID'] %>
      token:  <%= ENV['XACT_WEBHOOK_USER_TOKEN'] %>
      email_address: 'development-webhooks-test@govdelivery.com'
  sms_endtoend:
    xact:
      account:
        id: <%= ENV['XACT_SMSENDTOEND_ACCOUNT_ID'] %>
      token: <%= ENV['XACT_SMSENDTOEND_USER_TOKEN'] %>
      email_address: 'development-sms_end_to_end-test@govdelivery.com'
  email_endtoend:
    xact:
      account:
        id: <%= ENV['XACT_EMAILENDTOEND_ACCOUNT_ID'] %>
      token: <%= ENV['XACT_EMAILENDTOEND_USER_TOKEN'] %>
      email_address: 'development-email_end_to_end-test@govdelivery.com'
  sms_keyword_commands_stop:
    xact:
      account_id: <%= ENV['XACT_SMS2WAYSTOP_ACCOUNT_ID'] %>
      token: <%= ENV['XACT_SMS2WAYSTOP_USER_TOKEN'] %>
      email_address: 'development-sms_2way_stop-test@govdelivery.com'
  sms_keyword_commands_subscribe:
    xact:
      account:
        id: <%= ENV['XACT_SMS2WAYSUBSCRIBE_ACCOUNT_ID'] %>
      token: <%= ENV['XACT_SMS2WAYSUBSCRIBE_USER_TOKEN'] %>
      email_address: 'development-sms_2way_subscribe-test@govdelivery.com'
