encoded_link_prefix: 'https://odlinks.govdelivery.com'
evolution:
  account:
    email_address: 'autocukeprod_sa@evotest.govdelivery.com'
    password: 'govdel01!'
  api_url: 'https://api.govdelivery.com/api/account/CUKEAUTO_PROD/subscribers/'
accounts:
  email_endtoend:
    xact:
      account:
        id: '10220'
      email_address: 'CUKEPROD@govdelivery.com'
      password: 'GovDel01'
      email_address: 'production-email_end_to_end-test@govdelivery.com'
      from_address_two: 'production-email_end_to_end-test2@govdelivery.com'
      reply_to_address: 'productionemail_end_to_end-reply@govdelivery.com'
      reply_to_address_two: 'productionemail_end_to_end-reply2@govdelivery.com'
      bounce_address: 'production-email_end_to_end-errors@govdelivery.com'
      bounce_address_two: 'production-email_end_to_end-errors2@govdelivery.com'
      token: '7sRewyxNYCyCYXqdHnMFXp8PSvmpLqRW'
    gmail:
      imap:
        user_name: 'canari4dd+4@gmail.com'
