---
odm_uri: "http://localhost:65080"
odm_username: "test"
odm_password: "test"
fema_uri: "https://fema.gov.test/IPAWS_CAPService/IPAWS"
dcm_uri: "http://evolution.local:3001"
dcm_username: "test@sink.govdelivery.com"
dcm_password: "test"
analytics_enabled: true
analytics_kafkas: ["localhost:5468"]
redis_uri: "redis://localhost:6379/1"
allowed_geckoboard_accounts: [10_000]
