---
# required
#odm_uri: 'fake'
#odm_username: 'fake'
#odm_password: 'fake'
#fema_uri: 'fake'
#dcm_uri: 'fake'
#dcm_username:
#dcm_password:
#redis_uri:

# optional
analytics_enabled: false
analytics_kafkas: []
analytics_zookeepers: []
redis_sentinel_uris: [] # optional for environments with
nsca_password: ""       # for nagios alerting
shared_phone_numbers:
  - '+16514336311' # dev
  - '+16519684981' # qc
  - '+18573665390' # qc
  - '+19177468378' # int
  - '+16122604683' # stage
  - '468311'       # production
  # 89568 467873 566948 734876 667873 99511 - production short codes (as of 4/2015)
  # TXLOT INSURE KNOWIT seguro MNSURE WY511 - don't forward these, stop commands will handle unsubscribing
secret_key_base: #nil
mblox_api_key: 09047bedd24a450b9a037e34b59029df
mblox_service_account: govdeliverytest

# set these to run seed data
#twilio_sid: 'fake'
#twilio_token: 'fake'
#twilio_number: 'fake'
#twilio_test_sid: 'fake'
#twilio_test_token: 'fake'

use_simple_link_detection: true
