---
defaults: &defaults
  url: 'redis://localhost:6379'
  sidekiq_db: '1'
  sidekiq_namespace: 'xact'
development:
  <<: *defaults
test:
  <<: *defaults
ci:
  <<: *defaults
  url: 'redis://it-buildbox1.office.gdi:6379'
  sidekiq_db: '2'
qc-ep:
  <<: *defaults
  url: 'redis://qc-xactredis-master-ep.tops.gdi:6379'
qc:
  <<: *defaults
  url: 'redis://qc-xactredis-master-ep.tops.gdi:6379'
integration-ep:
  <<: *defaults
  url: 'redis://int-xactredis-master-ep.tops.gdi:6379'
integration:
  <<: *defaults
  url: 'redis://int-xactredis-master-ep.tops.gdi:6379'
stage-ep:
  <<: *defaults
  url: 'redis://stg-xactredis-master-ep.tops.gdi:6379'
stage:
  <<: *defaults
  url: 'redis://stg-xactredis-master-ep.tops.gdi:6379'
production:
  <<: *defaults
  url: 'redis://prod-xactredis-master-ep.tops.gdi:6379'
production-ep:
  <<: *defaults
  url: 'redis://prod-xactredis-master-ep.tops.gdi:6379'
