# get the queue key for the thing you want
# e.g.
#     Odm::TmsExtendedSenderWorker.sidekiq_options[:throttle_key].call({})
#
---
#sender:
#  interval: 15
#  limit: 5
sender_hi_im_billy:
  interval: 60
  limit: 1000