---
<%
  configuration = YAML.load_file('config/database.yml')[(ENV['RAILS_ENV'] || 'development')]
  database      = configuration["database"]
  username      = configuration["username"]
  password      = configuration["password"]
%>
jruby_min_runtimes: 1
jruby_max_runtimes: 1
address: 0.0.0.0
extensions:
  scheduler:
    # trinidad_scheduler_extension
  oracle_dbpool:
    # this should be the same as what is in database.yml
    jndi: jdbc/xact
    # expected to be 'host.gdi:port/service_name'
    url: jdbc:oracle:thin:@//<%=database%>
    username: <%=username%>
    password: <%=password%>
    maxActive: 10
    minIdle: 0
    minEvictableIdleTimeMillis: 10000
    maxIdle: -1
    maxWait: 10000
    testOnBorrow: true
    removeAbandoned: true
    logAbandoned: true
    validationQuery: SELECT 1 FROM dual
    validationInterval: 30000
    accessToUnderlyingConnectionAllowed: true
http:
  # incoming trafffc in deployed envs comes via ajp (except from nagios)
  acceptCount: 5
  maxThreads: 1
ajp:
  maxThreads: 15
  port: 8009
  connectionTimeout: 600000
