---
<%
  rails_env = ENV['RAILS_ENV'] || 'development'
  configuration = YAML.load_file('config/database.yml')[rails_env]
  database      = configuration["database"]
  username      = configuration["username"]
  password      = configuration["password"]
  debug = ['development', 'qc'].include?(rails_env)
%>
jruby_min_runtimes: 1
jruby_max_runtimes: 1
address: 0.0.0.0
http:
  # incoming traffic in deployed envs comes via ajp (except from nagios or in dev)
  acceptCount: 100
  maxThreads: 1
ajp:
  maxThreads: 100
  port: 8009
  connectionTimeout: 600000

