---
<%
  rails_env = ENV['RAILS_ENV'] || 'development'
  configuration = YAML.load_file('config/database.yml')[rails_env]
  database      = configuration["database"]
  username      = configuration["username"]
  password      = configuration["password"]
%>
jruby_min_runtimes: 1
jruby_max_runtimes: 1
address: 0.0.0.0
extensions:
  generic_dbpool:
    factory: org.apache.tomcat.jdbc.pool.DataSourceFactory
    <%- if
    <%= "jdbcInterceptors: 'ConnectionState;SlowQueryReportJmx(threshold=500,maxQueries=500)'" if ['development', 'qc'].include?(rails_env) %>
    driverPath: 'lib/ojdbc6.jar'
    driverName: 'oracle.jdbc.driver.OracleDriver'
    initSQL: SELECT 2 FROM DUAL
    # this should be the same as what is in database.yml
    jndi: jdbc/xact
    # expected to be 'host.gdi:port/service_name'
    url: jdbc:oracle:thin:@//<%=database%>
    username: <%=username%>
    password: <%=password%>
    initialSize: 10
    maxActive: 25
    maxIdle: 10
    minIdle: 3
    maxAge: 3600000
    minEvictableIdleTimeMillis: 1200000
    timeBetweenEvictionRunsMillis: 60000
    maxWait: 10000
    suspectTimeout: 15 #seconds
    logAbandoned: true
    removeAbandoned: true
    removeAbandonedTimeout: 60 #seconds
    testOnBorrow: false
    testWhileIdle: true
    validationQuery: SELECT 1 FROM dual
    validationInterval: 60000
http:
  # incoming traffic in deployed envs comes via ajp (except from nagios)
  acceptCount: 5
  maxThreads: 1
ajp:
  maxThreads: 100
  port: 8009
  connectionTimeout: 600000
