---
<%
  configuration = YAML.load_file('config/database.yml')[(ENV['RAILS_ENV'] || 'development')]
  database      = configuration["database"]
  username      = configuration["username"]
  password      = configuration["password"]
%>
jruby_min_runtimes: 1
jruby_max_runtimes: 1
address: 0.0.0.0
extensions:
  generic_dbpool:
    driverPath: 'lib/ojdbc6.jar'
    driverName: 'oracle.jdbc.driver.OracleDriver'
    initSQL: SELECT 2 FROM DUAL
    # this should be the same as what is in database.yml
    jndi: jdbc/xact
    # expected to be 'host.gdi:port/service_name'
    url: jdbc:oracle:thin:@//<%=database%>
    username: <%=username%>
    password: <%=password%>
    maxActive: 20
    minIdle: 5
    maxIdle: 15
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 30000
    maxWait: 10000
    suspectTimeout: 30
    removeAbandonedTimeout: 60
    logAbandoned: true
    testOnBorrow: true
    validationQuery: SELECT 1 FROM dual
    validationInterval: 60000
    accessToUnderlyingConnectionAllowed: true
http:
  # incoming traffic in deployed envs comes via ajp (except from nagios)
  acceptCount: 5
  maxThreads: 1
ajp:
  maxThreads: 100
  port: 8009
  connectionTimeout: 600000
