---
<%
  rails_env = ENV['RAILS_ENV'] || 'development'
  configuration = YAML.load_file('config/database.yml')[rails_env]
  database      = configuration["database"]
  username      = configuration["username"]
  password      = configuration["password"]
  debug = ['development', 'qc'].include?(rails_env)
%>
jruby_min_runtimes: 1
jruby_max_runtimes: 1
address: 0.0.0.0
extensions:
  generic_dbpool:
    jndi: jdbc/xact
    #uncomment to use tomcat-dbcp and disable tomcat-jdbc
    #pool: dbcp
    driverPath: 'lib/ojdbc6.jar'
    driverName: 'oracle.jdbc.driver.OracleDriver'
    url: jdbc:oracle:thin:@//<%=database%>
    username: <%=username%>
    password: <%=password%>
    initialSize: 25
    maxActive: 25
    maxIdle: 5
    minIdle: 5
    minEvictableIdleTimeMillis: 60000
    timeBetweenEvictionRunsMillis: 30000
    maxWait: 10000
    logAbandoned: <%= debug.to_s %>
    removeAbandonedTimeout: 60 #seconds
    removeAbandoned: true
    testOnBorrow: true
    testWhileIdle: false
    testOnReturn: true
    validationQuery: SELECT 1 FROM dual

    # **** tomcat-jdbc specific properties ****
    #jdbcInterceptors: 'ConnectionState'
    initSQL: SELECT 2 FROM DUAL
    suspectTimeout: 30
    validationInterval: 10000
    logValidationErrors: <%= debug.to_s %>
    maxAge: 3600000
http:
  # incoming traffic in deployed envs comes via ajp (except from nagios)
  acceptCount: 5
  maxThreads: 1
ajp:
  maxThreads: 100
  port: 8009
  connectionTimeout: 600000
