// Fetch Mailings State Types
export const FETCH_MAILINGS = 'FETCH_MAILINGS'
export const FETCH_MAILINGS_SUCCESS = 'FETCH_MAILINGS_SUCCESS'
export const FETCH_MAILINGS_FAILURE = 'FETCH_MAILINGS_FAILURE'
